# Instructions

- This homework assignment is worth **53** points. 
- Please strive for clarity and organization.
- **AI Usage**:
   - AI use is strictly **prohibited** for conceptual exercises.
   - For applied (Python) exercises, you may only use AI for **debugging**. Do not use AI to generate answers.
- **Due Date: October 2, 2026, by 11:59 PM.**

# Exercise 1 

In this exercise, we will practice how to apply the pandas `apply()` function on the `diamonds.csv` file. The `diamonds.csv` dataset contains the prices and other characteristics of almost 54,000 diamonds. For more information, see this [link](https://www.kaggle.com/datasets/shivam2503/diamonds).

### Exercise 1(a) (2 points)

Load `pandas` and `numpy`.

In [1]:
import pandas as pd
import numpy as np

### Exercise 1(b) (2 points)

Read the `diamonds` data file, and create a data frame called `diamonds`.

In [12]:
diamonds = pd.read_csv("diamonds.csv")

### Exercise 1(c) (2 points)

Create a lambda function called `carat_flag` that flags diamonds with `carat` values greater than 2.

In [7]:
carat_flag = lambda x: x > 2

### Exercise 1(d) (2 points)

Create a new column `flagging_carat`, using `apply`, that stores the value of `carat_flag` applied to `carat` column.

In [6]:
diamonds["flaggin_carat"] = diamonds["carat"].apply(carat_flag)
print(diamonds.head())

   Unnamed: 0  carat      cut color clarity  depth  table  price     x     y  \
0           1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98
1           2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84
2           3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07
3           4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23
4           5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35

      z  flaggin_carat
0  2.43          False
1  2.31          False
2  2.31          False
3  2.63          False
4  2.75          False

### Exercise 1(e) (6 points)

Convert the `cut`, `color`, and `clarity` columns to 0-1 columns, and append them to the `diamonds` data frame. Then, drop `cut`, `color`, and `clarity` from the data frame.

In [15]:
dummy_columns = pd.get_dummies(diamonds[["cut", "color", "clarity"]], dtype=int)

diamonds = pd.concat([diamonds, dummy_columns], axis=1)

diamonds = diamonds.drop(columns=["cut", "color", "clarity"])

In [16]:
diamonds.head()

,Unnamed: 0,carat,depth,table,price,x,y,z,cut_Fair,cut_Good,...,color_I,color_J,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,1,0.23,61.5,55.0,326,3.95,3.98,2.43,0,0,...,0,0,0,0,0,1,0,0,0,0
1,2,0.21,59.8,61.0,326,3.89,3.84,2.31,0,0,...,0,0,0,0,1,0,0,0,0,0
2,3,0.23,56.9,65.0,327,4.05,4.07,2.31,0,1,...,0,0,0,0,0,0,1,0,0,0
3,4,0.29,62.4,58.0,334,4.20,4.23,2.63,0,0,...,1,0,0,0,0,0,0,1,0,0
4,5,0.31,63.3,58.0,335,4.34,4.35,2.75,0,1,...,0,1,0,0,0,1,0,0,0,0

### Exercise 1(f) (4 points)

Create a lambda function called  `ratio` that computes the ratio of `depth` and `table`. Then, create a column called `depth/table`, using the `apply` function, that stores the values of `ratio` applied to the `diamonds` data frame.

In [17]:
ratio = lambda row: row["depth"] / row["table"]

diamonds["depth/table"] = diamonds.apply(ratio, axis=1) 

diamonds[["depth", "table", "depth/table"]].head()

   depth  table  depth/table
0   61.5   55.0     1.118182
1   59.8   61.0     0.980328
2   56.9   65.0     0.875385
3   62.4   58.0     1.075862
4   63.3   58.0     1.091379

### Exercise 1(g) (4 points)

Create a lambda function called `vol` that computes the product of `x`, `y`, and `z`. Then, create a column called `volume`, using the `apply` function, that stores the values of `vol` applued to the `diamonds` data frame.

In [18]:
vol = lambda row: row["x"] * row["y"] * row["z"] 

diamonds["volume"] = diamonds.apply(vol, axis=1)

diamonds[["x", "y", "z", "volume"]].head()

      x     y     z     volume
0  3.95  3.98  2.43  38.202030
1  3.89  3.84  2.31  34.505856
2  4.05  4.07  2.31  38.076885
3  4.20  4.23  2.63  46.724580
4  4.34  4.35  2.75  51.917250

# Exercise 2

In this exercise, we will practice object-oriented-programming concepts.

### Exercise 2(a) (12 points)

Create a class called `DataProcessing`. The class should include the following methods:

- `__init__(self, data: pd.DataFrame)`: Initializes the class with a pandas DataFrame.
- `encode_categorical(self, columns)`: Encodes categorical columns using `get_dummies` encoding from `pandas`. 
- `volume(self)`: Computes the volume of the diamond as `x * y * z`.
- `ratio(self)`: Computes the ratio of `depth` and `table`.
- `stand(self)`: Computes the z-score standardization of `carat`. That is, `(carat - mean(carat)) / std(carat)`, where `mean` and `std` are the mean and standard deviation, respectively.
- `fe(self)`: Append the `volume` and `ratio` engineered features to the data frame. Also apply `stand`.

Implement the `DataProcessing` class with the above methods and demonstrate its usage with a sample DataFrame.

In [22]:
class DataProcessing:
    def __init__(self, data: pd.DataFrame):
        self.data = data.copy()

    def encode_catergorical(self, columns):
        self.data = pd.get_dummies(
            self.data, columns=columns, dtype=int
        )
        return self.data 

    def volume(self):
        return self.data["x"] * self.data["y"] * self.data["z"] 

    def ratio(self):
        return self.data["depth"] / self.data["table"]

    def stand(self):
        carat = self.data["carat"]
        self.data["carat"] = (carat - carat.mean()) / carat.std() 

    def fe(self):
        self.data["volume"] = self.volume()
        self.data["depth/table"] = self.ratio()
        self.stand()
        return self.data

# Demonstrate the class with a sample DataFrame
sample = pd.DataFrame({
    "carat": [0.5, 1.0, 1.5],
    "cut": ["Good", "Ideal", "Premium"],
    "depth": [61.0, 62.0, 63.0],
    "table": [55.0, 56.0, 57.0],
    "x": [4.0, 5.0, 6.0],
    "y": [4.1, 5.1, 6.1],
    "z": [2.5, 3.0, 3.5]
}) 

sample_processor = DataProcessing(sample)
sample_processor.encode_catergorical(["cut"])
sample_processor.fe()

,carat,depth,table,x,y,z,cut_Good,cut_Ideal,cut_Premium,volume,depth/table
0,-1.0,61.0,55.0,4.0,4.1,2.5,1,0,0,41.0,1.109091
1,0.0,62.0,56.0,5.0,5.1,3.0,0,1,0,76.5,1.107143
2,1.0,63.0,57.0,6.0,6.1,3.5,0,0,1,128.1,1.105263

### Exercise 2(b) (2 points)

Using `read_csv` from `pandas`, read the `diamonds.csv` data file.

In [23]:
diamonds = pd.read_csv("diamonds.csv")

### Exercise 2(c) (3 points)

Initialize the `DataProcessing` class, and then run the `fe` method on the data frame.

In [24]:
processor = DataProcessing(diamonds)
diamonds = processor.fe()

diamonds.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,volume,depth/table
0,1,-1.198157,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,38.202030,1.118182
1,2,-1.240350,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,34.505856,0.980328
2,3,-1.198157,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,38.076885,0.875385
3,4,-1.071577,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,46.724580,1.075862
4,5,-1.029384,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,51.917250,1.091379

# Exercise 3

In this exercise, we will practice conceptual understanding of the object-oriented programming (OOP) and functional programming (FP) paradigms discussed in this chapter.

### Exercise 3(a) (3 points)

In your own words, define the four core principles of object-oriented programming (OOP): encapsulation, abstraction, inheritance, and polymorphism. For each principle, provide one concrete example using the `DataProcessing` class you built in Exercise 2 (or another pandas/scikit-learn object of your choice).

Encapsulation - Keeping data and the methods that work on it together in one object. In DataProcessing, self.data stores the DataFrame, and methods such as stand() process that data.

Abstraction - This provides a simple way to use something without needing to know every internal step. Calling processor.fe() adds volume along with ratio to standarize carat without requiring me to write those steps again.

Inheritance - This allows a new class to reuse methods from an existing class. For example, PriceFlagging can inherit from DataProcessing and use the fe() method while adding a price-flagging method.

Polymorphism - This allows the same method na,e to have different behavior for different objects. For example, a subclass could override stand() to standardize price instead of carat and calling stand() would then use the version defined for that object.

### Exercise 3(b) (3 points)

Compare and contrast the object-oriented programming (OOP) and functional programming (FP) paradigms. In your answer, address:

- What each paradigm treats as the primary building block of a program.
- One advantage of each paradigm.
- A scenario in a data science project where you would prefer OOP over FP, and vice versa.

1. OOP uses objects as its main building blocks. Objects combine data with methods that work on that data. Functional programming uses functions as its main building blocks, emphasizing functions that return results without chnaging the orginal data.

2. OOP keeps related data and operations organized together while FP functions without side effects are easier to test because the same inputs produce the same outputs.

3. OOP would be best for reusable data-processing tool that stores a dataset and provides several processing methods. Vice versa, I would prefer FP for a sequence of independent transformations, such as cleaning missing values, converting units, and calculatinf new features, with each function returning its result.

# Exercise 4

In this exercise, we will practice inheritance and polymorphism by extending the `DataProcessing` class built in Exercise 2.

### Exercise 4(a) (4 points)

Create a class called `PriceFlagging` that inherits from `DataProcessing`. The class should include a method `flag_price(self, threshold)` that creates a new column called `price_flag`, using `apply` and a lambda function, that stores 1 if `price` is greater than `threshold` and 0 otherwise.

In [25]:
class PriceFlagging(DataProcessing):
    def flag_price(self, threshold):
        self.data["price_flag"] = self.data["price"].apply(
            lambda price: 1 if price > threshold else 0
        ) 
        return self.data

### Exercise 4(b) (4 points)

Read the `diamonds.csv` data file. Initialize the `PriceFlagging` class, run the inherited `fe` method, and then call `flag_price` with a `threshold` of 10000. Display the first five rows of the resulting data frame.

In [26]:
diamonds = pd.read_csv("diamonds.csv")

price_processor = PriceFlagging(diamonds)
price_processor.fe()
price_processor.flag_price(10000)

price_processor.data.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,volume,depth/table,price_flag
0,1,-1.198157,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,38.202030,1.118182,0
1,2,-1.240350,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,34.505856,0.980328,0
2,3,-1.198157,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,38.076885,0.875385,0
3,4,-1.071577,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,46.724580,1.075862,0
4,5,-1.029384,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,51.917250,1.091379,0